### ISSUE TITLE
chainlit relatim-assistant not working in local observing panics

### ISSUE THREAD

**Issue by adhil-tinvio** [Chainlit/cookbook#148]
Was trying out chainlit realtime-assistant in local
could see these errors like below audio recording.
how can i fix this to test things out in local.

Log Trace:
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 109, in _receive_messages
    self.dispatch(f"server.{event['type']}", event)
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 66, in dispatch
    handler(event)
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 434, in _on_speech_stopped
    self._process_event(event, self.input_audio_buffer)
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 424, in _process_event
    item, delta = self.conversation.process_event(event, *args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 176, in process_event
    return event_processor(self, event, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 146, in <lambda>
    'input_audio_buffer.speech_stopped': lambda self, event, input_audio_buffer: self._process_speech_stopped(event, input_audio_buffer),
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adhile/cookbook/realtime-assistant/realtime/__init__.py", line 268, in _process_speech_stopped
    speech = self.queued_speech_items[item_id]
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'item_AG19J1QC1KjVkIBVgWiOL'```

**Comment by willydouhard** [comment]
is it happening randomly or are you able to reproduce?

**Comment by adhil-tinvio** [comment]
@willydouhard 
it is happening everytime.
i was trying to spawn this locally and see how it works to adap to our tool
i can record audio and when i complete recording it just stays same.
i can see these logs in my terminal

**Comment by adhil-tinvio** [comment]
FYI,i am just cloning this repo and testing out in my local.
that should be working?

**Comment by willydouhard** [comment]
> @willydouhard it is happening everytime. i was trying to spawn this locally and see how it works to adap to our tool i can record audio and when i complete recording it just stays same. i can see these logs in my terminal

Are you running the cookbook as is or modified?

**Comment by willydouhard** [comment]
> FYI,i am just cloning this repo and testing out in my local. that should be working?

it should

**Comment by MichaelRamirez043** [comment]
Closing based on evidence: PR #202 merged to main
