### ISSUE TITLE
OPenai realtime cookbook example incorrect pacages import

### ISSUE THREAD

**Issue by akashAD98** [Chainlit/cookbook#162]
from openai import AsyncOpenAI
& from realtime import RealtimeClient

im getting model not found issue & this pacages also im not able to find it out in pip . please help me with this

**Comment by WasamiKirua** [comment]
actually on run i am getting: 

```
2025-01-20 17:01:51 - Loaded .env file
Traceback (most recent call last):
  File "/Volumes/Data/opt/anaconda3/envs/chain/bin/chainlit", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 214, in chainlit_run
    run_chainlit(target)
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 78, in run_chainlit
    load_module(config.run.module_name)
  File "/Volumes/Data/opt/anaconda3/envs/chain/lib/python3.11/site-packages/chainlit/config.py", line 411, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Data/cookbook/realtime-assistant/app.py", line 9, in <module>
    from realtime import RealtimeClient
  File "/Volumes/Data/cookbook/realtime-assistant/realtime/__init__.py", line 464
    logger.error(f"Tool call error: {json.dumps({"error": str(e)})}")
                                                  ^^^^^
SyntaxError: f-string: unmatched '{'
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1737388914.467837  469098 init.cc:232] grpc_wait_for_shutdown_with_timeout() timed out.
(chain) (base) 
```

**Comment by MichaelRamirez043** [comment]
Closing based on evidence: PR #203 merged to main
