### ISSUE TITLE
Open AI Assitant functions

### ISSUE THREAD

**Issue by ronfromhp** [Chainlit/cookbook#41]
error:
Traceback (most recent call last):
  File "D:\Documendz\code-python\LLM chat app\aienv\lib\site-packages\chainlit\utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "D:\Documendz\code-python\LLM chat app\app2.py", line 120, in run_conversation
    if tool_call.type == "code_interpreter":
AttributeError: 'dict' object has no attribute 'type'

code:
```python
    # Periodically check for updates
    while True:
        run = await client.beta.threads.runs.retrieve(
            thread_id=thread.id, run_id=run.id
        )

        
        # Fetch the run steps
        run_steps = await client.beta.threads.runs.steps.list(
            thread_id=thread.id, run_id=run.id, order="asc"
        )

        for step in run_steps.data:
            # Fetch step details
            run_step = await client.beta.threads.runs.steps.retrieve(
                thread_id=thread.id, run_id=run.id, step_id=step.id
            )
            step_details = run_step.step_details
            # Update step content in the Chainlit UI
            if step_details.type == "message_creation":
                thread_message = await client.beta.threads.messages.retrieve(
                    message_id=step_details.message_creation.message_id,
                    thread_id=thread.id,
                )
            
                await process_thread_message(message_references, thread_message)

            if step_details.type == "tool_calls":
                for tool_call in step_details.tool_calls:
                    if tool_call.type == "code_interpreter":
                        if not tool_call.id in message_references:
                            message_references[tool_call.id] = cl.Message(
                                author=tool_call.type,
                                content=tool_call.code_interpreter.input
                                or "# Generating code...",
                                language="python",
                                parent_id=context.session.root_message.id,
                            )
                            await message_references[tool_call.id].send()
                        else:
                            message_references[tool_call.id].content = (
                                tool_call.code_interpreter.input
                                or "# Generating code..."
                            )
                            await message_references[tool_call.id].update()

                        tool_output_id = tool_call.id + "output"

                        if not tool_output_id in message_references:
                            message_references[tool_output_id] = cl.Message(
                                author=f"{tool_call.type}_result",
                                content=str(tool_call.code_interpreter.outputs) or "",
                                language="json",
                                parent_id=context.session.root_message.id,
                            )
                            await message_references[tool_output_id].send()
                        else:
                            message_references[tool_output_id].content = (
                                str(tool_call.code_interpreter.outputs) or ""
                            )
                            await message_references[tool_output_id].update()
                            
                    elif tool_call.type == "retrieval":
                        if not tool_call.id in message_references:
                            message_references[tool_call.id] = cl.Message(
                                author=tool_call.type,
                                content="Retrieving information",
                                parent_id=context.session.root_message.id,
                            )
                            await message_references[tool_call.id].send()
                    
                    # below part doesnt work yet, crashes gpt for some reason
                    elif tool_call.type == "function":
                        function_name = tool_call.function.name
                        function_to_call = get_taxi_booking_information
                        function_args = json.loads(tool_call.function.arguments)
                        function_response = function_to_call(**function_args)
                        print(function_response)
                        if not tool_call.id in message_references:
                            message_references[tool_call.id] = cl.Message(
                                author=tool_call.type,
                                content=function_response,
                                parent_id=context.session.root_message.id,
                            )
                            await message_references[tool_call.id].send()
              

        await cl.sleep(1)  # Refresh every second

        if run.status in ["cancelled", "failed", "completed", "expired"]:
            break
```
all i tried to do was add a function type tool call in the same format as the other tool calls.
To reproduce this error/bug just add a function to the tools while initialising an assistant and then use this code

**Comment by willydouhard** [comment]
Just updated the example. I was mostly able to run your code, maybe update your open ai package?
I started to add support for functions. Right now it [stops the execution](https://github.com/Chainlit/cookbook/commit/dd9dbc4594757cce97cb3e82c801230b03ea59a7), what you want to do is to actually call your function and send the response to the assistant.

**Comment by ronfromhp** [comment]
My bad, sorry for not specifying exactly how the bug appears. Initially it will work like typical but once you specify your intent to run the custom function, it tries to execute the function which then triggers the exception.

**Comment by willydouhard** [comment]
Then the fault is in your own function code if I understand correctly?

**Comment by ronfromhp** [comment]
No i meant to say that this error happens no matter what function you use. You can define your own function and see what happens when you ask the model to call it.

**Comment by willydouhard** [comment]
Just updated the example again.
<img width="1097" alt="Screenshot 2023-11-15 at 22 54 07" src="https://github.com/Chainlit/cookbook/assets/13104895/13ba7436-b4ea-41ab-bac8-501c1039f9a8">
 Running openai example on weather function works on my end

**Comment by ronfromhp** [comment]
I keep running into the same error in my system even with the latest code. I think i'll leave this issue open for anyone with the same seemingly unreproducable problem.
for clarity i was using openai v1.3.0 and running on windows 11

**Comment by willydouhard** [comment]
What happens if you create an assistant with the example weather function and runs exactly the cookbook code?

**Comment by ronfromhp** [comment]
i did create an assistant with the weather function and ran the exact code in app.py in the cookbook and here's how it went.
![image](https://github.com/Chainlit/cookbook/assets/86925532/45c0356e-99c9-4e07-b50e-2a6eeade2fa4)

**Comment by ronfromhp** [comment]
```CodeToolCall(id='call_ISmaA6hGQKgpoB2lhakjcUQb', code_interpreter=CodeInterpreter(input='# Perform the simple arithmetic operation of 9 + 10\nresult = 9 + 10\nresult', outputs=[CodeInterpreterOutputLogs(logs='19', type='logs')]), type='code_interpreter')
2023-11-16 04:41:42 - HTTP Request: GET https://api.openai.com/v1/threads/thread_eUIg5Wo60YlEW273NzzHT9Nb/runs/run_QxbW6TGqrfOvtHZH4Jj3UX9w/steps/step_6LJRZKLldi8U1sYHnfXz3vcg "HTTP/1.1 200 OK"
.
.
.
https://api.openai.com/v1/threads/thread_eUIg5Wo60YlEW273NzzHT9Nb/runs/run_87WajPnIDvjVrSJjdldZHluo/steps/step_BVdLZBchbq2mCDJmubfsA3GD "HTTP/1.1 200 OK"
{'id': 'call_cj1ZciInLlfQHQD28GOrir4R', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location":"New York"}'}}
2023-11-16 04:42:53 - 'dict' object has no attribute 'type'
Traceback (most recent call last):
  File "D:\Documendz\code-python\LLM chat app\aienv\lib\site-packages\chainlit\utils.py", line 39, in wrapper     
    return await user_function(**params_values)
  File "D:\Documendz\code-python\LLM chat app\app2.py", line 117, in run_conversation
    if tool_call.type == "code_interpreter":
AttributeError: 'dict' object has no attribute 'type'
```
i wish i did this sooner to explain the bug

**Comment by willydouhard** [comment]
Okay, I still fail to understand why you get a dict when I get a class instance. An easy fix is too check 

```py
if isinstance(tool_call, dict):
  # process
else:
#process
```

**Comment by willydouhard** [comment]
Thank you for your feedback!

We can definitely make the code handle both of the cases (would love a PR btw) but this inconsistency still looks weird to me. Maybe we should open an issue on OpenAI's repo?

**Comment by dividor** [comment]
In case it's useful, I was able to resolve the issue by first creating a class ...

```
class DictToObject:
    def __init__(self, dictionary):
        for key, value in dictionary.items():
            setattr(self, key, value)
```

Then having this code to monitor tool_call and convert as-needed

```
if isinstance(tool_call, dict):
        print(tool_call)
        tool_call = DictToObject(tool_call)
        if tool_call.type == "function":
            function = DictToObject(tool_call.function)
            tool_call.function = function
        if tool_call.type == "code_interpreter":
            code_interpretor = DictToObject(tool_call.code_interpretor)
            tool_call.code_interpretor = code_interpretor
```

**Comment by ronfromhp** [comment]
i think a better way would be to check the pip freeze of willy's environment

**Comment by willydouhard** [comment]
I can provide that, also going to check openai's python sdk repo issues

**Comment by ModEnter** [comment]
I'm closing the issue since a solution has been merged. Thanks for your precious feedback
