### ISSUE TITLE
Add LangGraph example

### ISSUE THREAD

**Issue by constantinidan** [Chainlit/cookbook#98]
```
from dotenv import load_dotenv
load_dotenv()
import chainlit as cl

from langchain_community.tools.tavily_search import TavilySearchResults

tools = [TavilySearchResults(max_results=1)]

from langgraph.prebuilt import ToolExecutor

tool_executor = ToolExecutor(tools)

from langchain_openai import ChatOpenAI

# We will set streaming=True so that we can stream tokens
# See the streaming section for more information on this.
model = ChatOpenAI(temperature=0, streaming=True)

from langchain.tools.render import format_tool_to_openai_function

functions = [format_tool_to_openai_function(t) for t in tools]
model = model.bind_functions(functions)

from typing import TypedDict, Annotated, Sequence
import operator
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]


from langgraph.prebuilt import ToolInvocation
import json
from langchain_core.messages import FunctionMessage

# Define the function that determines whether to continue or not
def should_continue(state):
    messages = state['messages']
    last_message = messages[-1]
    # If there is no function call, then we finish
    if "function_call" not in last_message.additional_kwargs:
        return "end"
    # Otherwise if there is, we continue
    else:
        return "continue"

# Define the function that calls the model
def call_model(state):
    messages = state['messages']
    response = model.invoke(messages)
    # We return a list, because this will get added to the existing list
    return {"messages": [response]}

# Define the function to execute tools
def call_tool(state):
    messages = state['messages']
    # Based on the continue condition
    # we know the last message involves a function call
    last_message = messages[-1]
    # We construct an ToolInvocation from the function_call
    action = ToolInvocation(
        tool=last_message.additional_kwargs["function_call"]["name"],
        tool_input=json.loads(last_message.additional_kwargs["function_call"]["arguments"]),
    )
    # We call the tool_executor and get back a response
    response = tool_executor.invoke(action)
    # We use the response to create a FunctionMessage
    function_message = FunctionMessage(content=str(response), name=action.tool)
    # We return a list, because this will get added to the existing list
    return {"messages": [function_message]}


from langgraph.graph import StateGraph, END
# Define a new graph
workflow = StateGraph(AgentState)

# Define the two nodes we will cycle between
workflow.add_node("agent", call_model)
workflow.add_node("action", call_tool)

# Set the entrypoint as `agent`
# This means that this node is the first one called
workflow.set_entry_point("agent")

# We now add a conditional edge
workflow.add_conditional_edges(
    # First, we define the start node. We use `agent`.
    # This means these are the edges taken after the `agent` node is called.
    "agent",
    # Next, we pass in the function that will determine which node is called next.
    should_continue,
    # Finally we pass in a mapping.
    # The keys are strings, and the values are other nodes.
    # END is a special node marking that the graph should finish.
    # What will happen is we will call `should_continue`, and then the output of that
    # will be matched against the keys in this mapping.
    # Based on which one it matches, that node will then be called.
    {
        # If `tools`, then we call the tool node.
        "continue": "action",
        # Otherwise we finish.
        "end": END
    }
)

# We now add a normal edge from `tools` to `agent`.
# This means that after `tools` is called, `agent` node is called next.
workflow.add_edge('action', 'agent')

# Finally, we compile it!
# This compiles it into a LangChain Runnable,
# meaning you can use it as you would any other runnable
app = workflow.compile()


from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnableConfig

@cl.on_message
async def run_convo(message: cl.Message):
    #"what is the weather in sf"
    inputs = {"messages": [HumanMessage(content=message.content)]}
    
    res = app.invoke(inputs, config=RunnableConfig(callbacks=[
        cl.LangchainCallbackHandler(
            to_ignore=["ChannelRead", "RunnableLambda", "ChannelWrite", "__start__", "_execute"]
            # can add more into the to_ignore: "agent:edges", "call_model"
            # to_keep=

        )]))

    await cl.Message(content=res["messages"][-1].content).send()
```

**Comment by hrone-dev-satyammishra** [comment]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/bin/chainlit", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/cli/__init__.py", line 201, in chainlit_run
    run_chainlit(target)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/cli/__init__.py", line 66, in run_chainlit
    load_module(config.run.module_name)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/config.py", line 419, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "langraph_chainlit.py", line 76, in <module>
    workflow = StateGraph(AgentState)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 151, in __init__
    self._add_schema(state_schema)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 166, in _add_schema
    channels, managed = _get_channels(schema)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 688, in _get_channels
    for name, typ in get_type_hints(schema, include_extras=True).items()
  File "/opt/anaconda3/envs/myenv/lib/python3.9/typing.py", line 1450, in get_type_hints
    base_globals = sys.modules[base.__module__].__dict__

**Comment by hrone-dev-satyammishra** [comment]
Error Trace

Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/bin/chainlit", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/cli/__init__.py", line 201, in chainlit_run
    run_chainlit(target)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/cli/__init__.py", line 66, in run_chainlit
    load_module(config.run.module_name)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/chainlit/config.py", line 419, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "langraph_chainlit.py", line 77, in <module>
    workflow = StateGraph(AgentState)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 151, in __init__
    self._add_schema(state_schema)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 166, in _add_schema
    channels, managed = _get_channels(schema)
  File "/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/langgraph/graph/state.py", line 688, in _get_channels
    for name, typ in get_type_hints(schema, include_extras=True).items()
  File "/opt/anaconda3/envs/myenv/lib/python3.9/typing.py", line 1450, in get_type_hints
    base_globals = sys.modules[base.__module__].__dict__
KeyError: 'file_name.py'

**Comment by ModEnter** [comment]
The example has been added to the cookbook in [this PR](https://github.com/Chainlit/cookbook/pull/143). Concerning the issue you're encountering @hrone-dev-satyammishra, it seems related to your conda environment's typing. Please try using python instead, and make sure you use the latest Chainlit version
